### ISSUE TITLE
Allow only OPed players to do /limitedlives set

### ISSUE THREAD

**Issue by Ascellayn** [iChun/Limited-Lives#10]
Why is this even a thing
Fabric 1.19.2, mod version 1.2.1

Edit: Oh and the server is behind a velocity proxy, don't know if that matters

**Comment by iChun** [comment]
Oh. Oops.

**Comment by Darhlas** [comment]
The same issue is in the forge 1.19.2 version, mod version 1.2.0.

**Comment by iChun** [comment]
Was fixed by this commit. Unfortunately I won't be backporting the fix but you're welcome to build your own version if needed https://github.com/iChun/LimitedLives/commit/7d493eec659818b04b4964a597664805b1cf171a
