### ISSUE TITLE
Set Death Count Command Doesn't Work

### ISSUE THREAD

**Issue by MrRedstoneA1** [iChun/Limited-Lives#12]
I tried /ll, /limitedlives, !ll, !limitedlives but none of them let me set death count.
Versions
limitedlives 1.12.1-1.0.1
Forge 14.23.5.2860

**Comment by iChun** [comment]
Holy baloney, you're using a mod version from over 5 years ago. I'm sorry but I have no plans on supporting any of my mods for that far back. 

Obligatory: https://howoldisminecraft1122.today/

**Comment by MrRedstoneA1** [comment]
Yep, 1.12.2 is the version I'm still using. Most mods I use were never updated to newer versions, so I have no way or reason to switch.

**Comment by iChun** [comment]
Now that I think about it, using /ll set <target> <deaths> was only added later on when the mod was redone for later versions of Minecraft. 

If you want you can go back through the commit history and try to add it through the code. Commands in the 1.12.2 era were very different vs MC now.
