### ISSUE TITLE
The announcing of remaining lives in chat on respawn completely stops working when the config is edited.

### ISSUE THREAD

**Issue by Darhlas** [iChun/Limited-Lives#13]
Forge 1.19.2, mod version 1.2.0.
When changing any config settings in the mod's config file, the **announceOnRespawn** part completely stops working even when its set value is _true_.

**Comment by VeggeieDude** [comment]
Oooh that's why it's not working lol

**Comment by iChun** [comment]
I think I've fixed it, it'll be in the next update for MC 1.20.2
