### ISSUE TITLE
Fabric [1.20.1] Minecraft Server Error

### ISSUE THREAD

**Issue by madilizxd** [iChun/Limited-Lives#16]
[console report.txt](https://github.com/iChun/LimitedLives/files/14394099/console.report.txt)
Same mods, same API's, works fine in singleplayer. Complete Config version 2.5.0 is installed in both. But in the server, Limited Lives stops the console. 

Error: [main/ERROR]: Failed to start the minecraft server
[Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'main' due to errors, provided by 'limitedlives'!
-
Caused byjava.lang.NoSuchFieldError: checkbox

**Comment by iChun** [comment]
Fixed in the update porting configs to iChunUtil in place of CompleteConfig
