### ISSUE TITLE
[Request] min hearts and unlimited lives

### ISSUE THREAD

**Issue by stohun01** [iChun/Limited-Lives#3]
- A config option for minimum number of hearts. I'd like to set 1 heart (2 health points) as the minimum health capacity so you can still respawn but are extremely vulnerable. Then use items from other mods to gain hearts back.
- Increase the health adjust range in the config to 0-2 so each death can lose a whole heart.

**Comment by iChun** [comment]
Almost 5 years late, but done for version 1.2.0.
