### ISSUE TITLE
Adicionar corações ao jogador

### ISSUE THREAD

**Issue by MauBrineGM** [iChun/Limited-Lives#5]
Oi sou MauBrineGM crio mapas com mods da verção 1.7.10 "Nome Mineadventure Hardcore" eu uso o mod custon npc como principal mod e Cristal heart para almentar a vida do jogador , queria pergunta se tem como coloca um item para almentar o limite de vida sem se craft apenas clicar e almwntar para eu usar na  criaçao de mapa .

**Comment by iChun** [comment]
Olá, desculpe, mas não tenho mais suporte para a versão 1.7.10, considerando sua idade. https://howoldisminecraft1710.today/

Além disso, geralmente todos os rastreadores de problemas usam o inglês, então isso foi traduzido usando o Google Translate.

**Comment by MauBrineGM** [comment]
Nao estou falando para atualizar para 1.7.10 estou falando para ter um item para fazer o inverso o que o mod faz, diveis diminuir apos a morte ter um item que só o criativo pode ter que almenta a quatidade de vida assim eu posso criar Mapas de RPG na verção 1.18 adiante

**Comment by iChun** [comment]
Por que você desejaria tal item se ele só será usado no criativo?

**Comment by MauBrineGM** [comment]
Para eu poder criar as classes e bosses tipo , quando o jogador matar o boss vou fazer o boss dropar o coraçao para melhorar a vida do jogador assim deixando o jogador mais forte podendo assim deixar os mobs com mais vida e mais dano tendeu ,obrigando os jogadores a fazer quests para poder melhorar sua jogatina , eu crio mapas de RPG e ja fiz isso mas os mods que eu uso nao atualizou os mods se chaman ,Custon npc, e Cristal heart

**Comment by iChun** [comment]
então o que você está pedindo é basicamente um item que forneça recipientes de coração?

**Comment by iChun** [comment]
Ou você está procurando por versões atualizadas dos mods que você disse não terem sido atualizados? Ou talvez mods semelhantes?

Não tenho certeza se entendi muito bem o que você está pedindo, pois tenho que traduzir o que você está pedindo com o Google Translate.

**Comment by MauBrineGM** [comment]
Desculpe pela tradução,  mas sim seria adicionar um   item que forneça recipientes de coração , depois eu vejo se o criador do mod " Custon npc " atualiza o mod para nova verção

**Comment by iChun** [comment]
Nesse caso, você terá que procurar outro mod que faça isso, o que tenho certeza de que outros já fazem.

Este mod tem um propósito muito simples e foi escrito para não exigir instalação no cliente para funcionar.

Adicionar um item exigiria que o mod fosse instalado no cliente e não estaria dentro do meu objetivo para este mod.
