### ISSUE TITLE
Can't use config file

### ISSUE THREAD

**Issue by Rad586** [iChun/Limited-Lives#9]
Game version: 1.18.2 fabric
Mod version: 1.2.1
Description:
Can‘t change anything in config file, everytime I restart the game, it turns back to it's default value.

**Comment by iChun** [comment]
Is your game open whilst you edit the config? That causes the config file
to be overwritten when the game closes even if there's no changes as
suggested by CompleteConfig spec.

**Comment by Rad586** [comment]
Sorry, I didn't know that💀
